# Copyright 2016, 2017 Peter Dimov
# Copyright 2017 - 2019 James E. King III
# Copyright 2019 - 2021 Alexander Grund
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: false

branches:
  only:
    - master
    - develop
    - /bugfix\/.*/
    - /feature\/.*/
    - /fix\/.*/
    - /pr\/.*/

matrix:
  fast_finish: false
  # Adding MAYFAIL to any matrix job allows it to fail but the build stays green:
  allow_failures:
    - MAYFAIL: true

environment:
  global:
    B2_CI_VERSION: 1
    GIT_FETCH_JOBS: 4
    # see: http://www.boost.org/build/doc/html/bbv2/overview/invocation.html#bbv2.overview.invocation.properties
    # to use the default for a given environment, comment it out; recommend you build debug and release however:
    # on Windows it is important to exercise all the possibilities, especially shared vs static, however most
    # libraries that care about this exercise it in their Jamfiles...
    B2_ADDRESS_MODEL: 32,64
    B2_LINK: shared,static
    # B2_THREADING: threading=multi,single
    B2_VARIANT: release,debug
    # Include OpenCppCoverage and git bash (avoid WSL bash)
    PATH: 'C:\Program Files\OpenCppCoverage;C:\Program Files\Git\bin;%PATH%'
    # CODECOV_TOKEN: { secure: BUWmc1TLOFKpwqt5vE27s8j5nZKbEhq2s4BAUx2oap4dBrHEUPwdNScqfYBecLxm }
  matrix:
    - FLAVOR: Coverage VS 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      COVERAGE: true
      B2_CXXFLAGS: -permissive-
      B2_CXXSTD: 14,17,latest # 2a
      B2_TOOLSET: msvc-14.2

install:
  - git clone --depth 1 https://github.com/boostorg/boost-ci.git C:\boost-ci-cloned
  # Copy ci folder if not testing Boost.CI
  - if NOT "%APPVEYOR_PROJECT_NAME%" == "boost-ci" xcopy /s /e /q /i /y C:\boost-ci-cloned\ci .\ci
  - rmdir /s /q C:\boost-ci-cloned
  - ci\appveyor\install.bat

build: off

test_script: ci\build.bat

for:
  - matrix:
      only: [CMAKE: true]
    install: true
    before_build:
      - dir C:\Libraries
      - if exist build\ (rmdir /S /Q build)
      - set "INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\installed"
      - if exist %INSTALL_DIR%\ (rmdir /S /Q %INSTALL_DIR%)
      - mkdir build
      - cd build
      - cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% ..
    build_script: cmake --build . --config %configuration% --parallel 4
    test_script:
      - ctest --output-on-failure -C %configuration% --parallel 4
      - ps: |
            $iostream_exe = "$env:configuration/boost_nowide-test_iostream.exe"
            # Should show "Using Nowide input/output" and run the tests
            &$iostream_exe
      - ps: |
            If ($env:COVERAGE -eq "true") {
              choco install opencppcoverage
              Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
              OpenCppCoverage.exe --quiet --export_type cobertura:cobertura.xml `
                --sources ${env:APPVEYOR_BUILD_FOLDER} --modules "$PWD" `
                --excluded_line_regex '.*// LCOV_EXCL_LINE' `
                --excluded_line_regex '.*// coverity\[dead_error_line\]' `
                --excluded_line_regex '\s*[{}]*\s*' `
                --excluded_line_regex '\s*(\} )?else( \{)?\s*' `
                --cover_children --working_dir "$PWD" -- ctest -C Debug
              ./codecov.exe -n Appveyor -e APPVEYOR_BUILD_WORKER_IMAGE
            }
      # Build consumer example test
      - cmake --build . --config %configuration% --target install
      - del /F /S /Q *
      - cmake -DBOOST_NOWIDE_INSTALL_TEST=ON -G "%GENERATOR%" -DCMAKE_PREFIX_PATH=%APPVEYOR_BUILD_FOLDER%\installed ../test/cmake_test
      - cmake --build . --config %configuration%
      - ctest --output-on-failure -C %configuration% --parallel 4
  # Superproject CMake build
  - matrix:
      only: [COVERAGE: true]
    test_script: [ps: ci\codecov.ps1]
  # Superproject CMake build
  - matrix:
      only: [BOOST_CMAKE: true]
    branches:
      only: [develop] # Doesn't work on master yet
    test_script:
      - ps: |
            cd "$env:BOOST_ROOT"
            mkdir __build_static | cd
            cmake -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=1 -DBOOST_INCLUDE_LIBRARIES=nowide -DBUILD_TESTING=1 ..
            cmake --build . --config Debug --parallel 4
            ctest --output-on-failure --build-config Debug
            cmake --build . --config Release --parallel 4
            ctest --output-on-failure --build-config Release
            cd ..
            mkdir __build_shared | cd
            cmake -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=1 -DBUILD_SHARED_LIBS=ON -DBOOST_INCLUDE_LIBRARIES=nowide -DBUILD_TESTING=1 ..
            cmake --build . --config Debug --parallel 4
            ctest --output-on-failure --build-config Debug
            cmake --build . --config Release --parallel 4
            ctest --output-on-failure --build-config Release
  # Coverity build
  - matrix:
      only: [COVERITY: true]
    branches:
      only: [master, develop]
    init:
      - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -gt 0) {Exit-AppveyorBuild}
    install: true
    test_script:
      - cd build
      - cmake -G "%GENERATOR%" ..
      - ps: |
            nuget install -ExcludeVersion PublishCoverity
            cov-build.exe --dir cov-int cmake --build . --config $env:configuration
            If ($LastExitCode -ne 0) {
              cat cov-int/build-log.txt
              $host.SetShouldExit($LastExitCode)
            }
            PublishCoverity\tools\PublishCoverity.exe compress --nologo -i cov-int -o cov-int.zip --overwrite

            # This may fail due to a wrong HTTP 500 code from coverity, hence the stderr redirection via cmd
            # to make the build succeed anyway
            cmd /c PublishCoverity\tools\PublishCoverity.exe publish --nologo `
              -t "$env:COVERITY_SCAN_TOKEN" `
              -e "$env:COVERITY_SCAN_NOTIFICATION_EMAIL" `
              -r "$env:APPVEYOR_REPO_NAME" `
              -z "cov-int.zip" `
              -d "Appveyor build for $env:APPVEYOR_REPO_BRANCH" `
              --codeVersion "$env:APPVEYOR_REPO_BRANCH" 2`>`&1
            Write-Host "Done"
